### ISSUE TITLE
Changelogs for closed-source addons (PRO, DevTools, EditableColumns etc.)

### ISSUE THREAD

**Issue by niladam** [Laravel-Backpack/ideas#156] opened 2022-03-15 08:52 UTC
# Feature Request

### What's the feature you think Backpack should have?

A way to view `backpack/pro` changelogs

### Have you already implemented a prototype solution, for your own project?

not applicable

### Do you see this as a core feature or an add-on?

core feature.

Hey @tabacitu,

Since the move to `backpack/pro` repository, i am unable to find any changelogs about this anywhere. I would like to be able to know what change since i sometimes modify the fields/columns and a view into that would allow me to simply merge the changes myself.

Thank you.

**Comment by tabacitu** [comment] 2022-07-18 12:28
Good news! 

@phpfour will take this over, and try to figure out the best solution. Right now it's between:
- (A) Using a Github action that will automatically write inside the changelog file (downside: that writing happens _after_ the tag has been pushed, so the edited changelog is NOT part of the tag itself; that means online visitors will always see the next-to-last version; unleeess... we actually show the changelog from `master`/`main`... in which case that'll get solved;);
- (B) Coding our own Github API integration, to show the release notes on a web page;

So while we haven't _actually_ made progress on this... we will 😅 Soon!

**Comment by phpfour** [comment] 2022-08-11 05:02
Hey @tabacitu I was able to get the changelog generation work with the unreleased tag: 

![Image](https://user-images.githubusercontent.com/171715/184067387-b574b6fd-0236-4436-9c65-214b5791ffa8.png)

**Comment by phpfour** [comment] 2022-08-11 05:04
Now, working on the last piece of the puzzle: 

- persist the full release note
- ensure proper markdown formatting

![Image](https://user-images.githubusercontent.com/171715/184067559-48f855c9-085d-4e21-8da3-b8f16999a868.png)

**Comment by phpfour** [comment] 2022-08-11 14:04
Hey @tabacitu, I've cracked the last issue and now it generates pretty release details. I've also made the changelog format simpler (without the sections). Let me know what you think! 

Here's the repository if you want to play with it: https://github.com/phpfour/changelog-tag-release-action

### Changelog
![Image](https://user-images.githubusercontent.com/171715/184151287-130a9911-f0ea-43d1-8fa5-9592aefb8340.png)

### Release
![Image](https://user-images.githubusercontent.com/171715/184151307-4b68f8b8-2c4b-4ccc-8507-c9368565d1e9.png)

**Comment by tabacitu** [comment] 2022-08-12 10:23
Looks AWESOME @phpfour 👏👏👏 I've added it to the DevTools repo, ran the action aaaand...

<img width="1505" alt="CleanShot 2022-08-12 at 13 19 46@2x" src="https://user-images.githubusercontent.com/1032474/184335127-58c08b5a-95f8-470f-a2da-cdc8a1d5741c.png">

There's a branch protection rule on `main`... only I can push to it. And it has to stay that way. Especially if in the future we give access to customers too, not just team members 🤦‍♂️  this is the bit that was failing in the first place, I think, in [our initial release action](https://github.com/Laravel-Backpack/DevTools/pull/292)... the fact that Github cannot make changes to a protected branch...

That's the big problem... now the question is... what can we do about it?... Any ideas?

**Comment by phpfour** [comment] 2022-08-13 17:41
Hey @tabacitu, in such cases a Personal Access Token (PAT) should be generated with the `repo` access and then it can be added to the repository secrets: 

![Repo Secrets](https://user-images.githubusercontent.com/171715/184504913-b2040c55-0d42-4fee-a350-abca61902917.png)

Afterwards, the token should be passed to the action's code checkout job: 

![Workflow](https://user-images.githubusercontent.com/171715/184504908-c79cf4ee-e4cc-4873-b251-679664047dc6.png)

I've updated the workflow to reflect this, so please copy the new code, define the secret and run the action. It worked on my case, let's see if it works for you :)

**Comment by tabacitu** [comment] 2022-08-16 12:35
IT WORKS!!! IT WORKSS!! Buut... not always 😅 Can you please investigate why we're having this rate limiting problem? 🙏

https://github.com/Laravel-Backpack/DevTools/runs/7857605161?check_suite_focus=true

**Comment by tabacitu** [comment] 2022-08-19 08:20
> IT WORKS!!! IT WORKSS!! Buut... not always 😅 Can you please investigate why we're having this rate limiting problem? 🙏

@phpfour please ignore that, for now. I've just run 4 release actions today (2x PRO, 1x DevTools, 1x EditableColumn) and haven't run into rate limiting. I don't know what the problem was back then but... we're good for now. It's unlikely we'll need to do more than 3 releases in one hour. If we have this problem again in the future, we'll investigate then. But for now, looks like we're ok.

**Update:** 
- I can confirm we now have up-to-date changelogs, for all our closed-source software:
    - [Backpack PRO](https://backpackforlaravel.com/products/pro-for-unlimited-projects/CHANGELOG.md)
    - [Backpack DevTools](https://backpackforlaravel.com/products/devtools/CHANGELOG.md)
    - [Backpack EditableColumns](https://backpackforlaravel.com/products/editable-columns/CHANGELOG.md)
- There are still ways we could/should improve the changelongs, so I've opened https://github.com/Laravel-Backpack/ideas/issues/199

Since we actually HAVE up-to-date changelogs now, I'm going to close this issue - let's continue the conversation in https://github.com/Laravel-Backpack/ideas/issues/199 about how to improve them. 

Thanks a lot @phpfour , I'm so so glad we finally have this 🎉 
I know figuring this out was a pain.

**Comment by tabacitu** [comment] 2022-11-09 06:08
@phpfour looks like our last changelog update introduced a bug. 

I just tagged a new version of `backpack/editable-columns` and instead of the changelog including only PR titles, it also includes closed issue titles.

Could you take a look and fix, please? 🙏

**Comment by phpfour** [comment] 2022-11-09 09:29
Hey @tabacitu, it's not a bug actually...this can be configured in the GH action, see the below doc (all are turned on by default): 

![CleanShot 2022-11-09-15 27 33](https://user-images.githubusercontent.com/171715/200792571-0ebe98ab-29c2-44df-96fd-56235b2570de.png)

I can update this in all the repositories if you'd like – let me know.

**Comment by tabacitu** [comment] 2022-11-12 07:48
Ah ok. Yes please 🙏 Let's only mention PRs.

**Closed** 2022-12-20 08:37 UTC
Labels: Priority: MUST, Feature Request
